### ISSUE TITLE
directly apply on the original point cloud

### ISSUE THREAD

**Issue by zhouzhou33** [charlesq34/frustum-pointnets#100]
Can it apply directly to the original point cloud and image without generating the pickle file?

**Comment by Sherlock-hh** [comment]
你好请问你搞定这个问题了吗？我也想用自己的点云和图片训练。

**Comment by zhouzhou33** [comment]
没有，后来直接舍弃这个方法了。=v= @Sherlock-hh

**Comment by Sherlock-hh** [comment]
> 没有，后来直接舍弃这个方法了。=v= @Sherlock-hh

好吧谢谢，心累，卡数据标注这老久了。

**Comment by Sherlock-hh** [comment]
兄弟，不好意思这么久又来打扰你了，请问你之前用frustum-pointnet做到哪一步了？他们原始的sunrgbd数据有测试结果了吗?或者是数据预处理成功了吗？有成功给这个算法加入2d检测吗?orz我已经跪倒在这个算法上一个月了。。希望你能帮帮我谢谢谢谢

**Comment by zhouzhou33** [comment]
@Sherlock-hh 你好，对于你的问题我也是爱莫能助。我之前用frustum在sunrgbd数据集上跑出了结果，但是训练好的模型在重装系统的时候忘记备份了。你说的数据预处理是matlab处理sunrgbd数据集吗，如果是的话那就成功过。至于2d检测，没有实现，因为我获取到深度数据之后一直没有搞懂相机之间的标定，代码中转换的过程不是很明白，所以没有成功实现。

**Comment by Sherlock-hh** [comment]
我刚做到matlab这一步，现在要继续运行sunrgbd_data.py了，但是这一步里面有个rgb_detection，也就是2d检测的结果。如果没有rgb_detection也会出结果吗？你有可视化结果吗？

**Comment by zhouzhou33** [comment]
@Sherlock-hh 处理完数据集之后，会生成四个文件夹吧，那四个文件夹里就有2d检测的结果呀。运行sunrgbd_data的时候会自动读取吧？不过我运行的是extract_roi_seg().我已经很久没再碰过这个代码了，忘得差不多了。(。_。)可视化的结果好像有两张。我翻一翻哈。

**Comment by Sherlock-hh** [comment]
你好我现在到了运行sunrgbd_data.py这一步去生成pickle文件了，运行之前要生成一个train_data_idx.txt和val_data_idx.txt，请问这个里面是写文件名就可以吗，例如000001.txt这样，还是要加上路径？只用train和val就可以吗，10355份数据train：val=8：2可以吗？
需要另外提取一部分作为test吗？

**Comment by zhouzhou33** [comment]
@Sherlock-hh 不用加txt，直接就是000001,000002这样子。只用训练集和数据集就可以了。比例不清楚，我只训练过。

**Comment by Sherlock-hh** [comment]
好嘞，程序跑起来了
![frustum-pointnet](https://user-images.githubusercontent.com/65853825/96843050-71a5e900-1480-11eb-8656-4e7e52c0dcac.png)
接下来就是直接按照作者readme 里面的python train_one_hot.py 然后一堆参数的吧。
谢谢哈，我再想办法搞一下2d检测，非常感谢回复！

**Comment by Sherlock-hh** [comment]
> @Sherlock-hh 处理完数据集之后，会生成四个文件夹吧，那四个文件夹里就有2d检测的结果呀。运行sunrgbd_data的时候会自动读取吧？不过我运行的是extract_roi_seg().我已经很久没再碰过这个代码了，忘得差不多了。(。_。)可视化的结果好像有两张。我翻一翻哈。

嗯！激动！有训练完的可视化的结果吗！加bounding box的那种吗？！

**Comment by zhouzhou33** [comment]
> > @Sherlock-hh 处理完数据集之后，会生成四个文件夹吧，那四个文件夹里就有2d检测的结果呀。运行sunrgbd_data的时候会自动读取吧？不过我运行的是extract_roi_seg().我已经很久没再碰过这个代码了，忘得差不多了。(。_。)可视化的结果好像有两张。我翻一翻哈。
> 
> 嗯！激动！有训练完的可视化的结果吗！加bounding box的那种吗？！

> 

- [](url)

**Comment by zhouzhou33** [comment]
你要不加我个联系方式我发你把。1604171773

> > @Sherlock-hh 处理完数据集之后，会生成四个文件夹吧，那四个文件夹里就有2d检测的结果呀。运行sunrgbd_data的时候会自动读取吧？不过我运行的是extract_roi_seg().我已经很久没再碰过这个代码了，忘得差不多了。(。_。)可视化的结果好像有两张。我翻一翻哈。
> 
> 嗯！激动！有训练完的可视化的结果吗！加bounding box的那种吗？！

**Comment by FeiDao7943** [comment]
请问文件夹里的2d检测的结果是不是在label_dimension/里的
