### ISSUE TITLE
Segmentation fault in Tensorflow version 1.14.0

### ISSUE THREAD

**Issue by witignite** [charlesq34/frustum-pointnets#103]
**Type**: Question
**OS**: Ubuntu 16.04
**TensorFlow**: `tensorflow-gpu-1.14.0`, installed with pip
**CUDA**: 10.0

I have compiled the custom operators in `/models/tf_ops/` folder successfully.

When I tried training with `tensorflow-gpu-1.14.0` installed with pip, the custom TensorFlow operators didn't seem to work. I stepped through the code and it breaks at the point where the code tries to call the custom op `sampling_module.farthest_point_sample(inp, npoint)` [here](https://github.com/charlesq34/frustum-pointnets/blob/2ffdd345e1fce4775ecb508d207e0ad465bcca80/models/tf_ops/sampling/tf_sampling.py#L57).

It results in a segmentation fault:
```bash
python train/train.py --gpu 0 --model frustum_pointnets_v2 --log_dir train/log_v2 --num_point 1024 --max_epoch 201 --batch_size 1 --decay_step 800000 --decay_rate 0.5
pid: 20105
Segmentation fault (core dumped)
```

**However**, when I tried with `tensorflow-1.12.0`, it seems to work fine.

I have completely no idea why it doesn't work with `tensorflow-gpu-1.14.0`, and I'm not very experienced with writing TensorFlow custom op.

Dear author, @charlesq34 , do you know what might be a possible reason? Or does anyone have a clue why it doesn't work with `1.14.0` version?

**Comment by witignite** [comment]
Probably it is because of mismatch compiler.

**Comment by anjingde** [comment]
When I eval the val ,I meet the same problem. How to mdeal with this problem?

Going to eval ground for class: pedestrian
Segmentation fault (core dumped)
