### ISSUE TITLE
pickle files only contain a list of int number

### ISSUE THREAD

**Issue by 300LiterPropofol** [charlesq34/frustum-pointnets#105]
Hi,
I downloaded the pickle file zip from the main page and unzip them. Then I load them in the workspace but I found the pickle file only contains a list of int instead of points coordinates, 2D box locations and categories information etc. 
Here is the screenshot.

I wonder why and what these int number mean? Can someone help me? Thank you.
![image](https://user-images.githubusercontent.com/46748408/75984443-aca3de00-5eea-11ea-9342-231bbd748c6d.png)

**Comment by 300LiterPropofol** [comment]
Solved, it is because of python version issue.

with open(data_path, 'rb') as fp:
    id_list = pickle.load(fp, encoding='latin1')
    box2d_list = pickle.load(fp, encoding='latin1')
    .......

use this code can fix the problem

**Comment by DevanshL** [comment]
can you provide pickle file here
