### ISSUE TITLE
End-to-end Training with 2D Proposals Generation?

### ISSUE THREAD

**Issue by Cogito2012** [charlesq34/frustum-pointnets#14]
Thanks for your excellent paper and released code.
It seems that the performance of your F-PointNet depends much on the 2D proposals from RGB detector. And from the supplementary of your arxiv paper, you have made great effort on the training of the RGB detector. I was wondering that if it is possible to train the RGB detector jointly with F-PointNet in an end-to-end fashion? Or this method may not work well ?

**Comment by charlesq34** [comment]
HI @Cogito2012 

Current pipeline makes the 2D detector and frustum pointnets separately, which is a conscious decision we made. This makes it easy to switch 2d detector very easily -- 2d datasets are often much larger in scale than 3d ones, any progress in current 2d detectors can also instantly be included into our pipeline without retraining the 3d part.

on the other side, in current pipeline there is actually no gradient flow from 3d nets to 2d nets -- so joint training will not lead to any extra benefits.

It would be an interesting research topic on how to jointly train 2d and 3d parts to improve performance.

**Comment by charlesq34** [comment]
(close due to inactivity)
