### ISSUE TITLE
How to restore the train?

### ISSUE THREAD

**Issue by louxy126** [charlesq34/frustum-pointnets#15]
Hi! @charlesq34!
I follow the readme.md to train the data and the train can start.But there is a problem with my computer.My computer is crashed after some epoch（random）.I noticed the train will be saved every 10 epoch，but when I restart my computer and use "CUDA_VISIBLE_DEVICES=0 sh scripts/command_train_v1.sh" to train.The train will begin from epoch0. How can I restore the train from the step that my computer was crashed?
Thanks!

**Comment by charlesq34** [comment]
Hi @louxy126 
There is a `--restore_model_path` flag in the `train.py`

you can set that to the most current `ckpt` file you have such as `log_v1/model.ckpt` 
then the training will start from that snapshot.

hope it helps
