### ISSUE TITLE
Using Pickle Files

### ISSUE THREAD

**Issue by zemahran** [charlesq34/frustum-pointnets#19]
Such great work Charles! I wanted to know if using the newly uploaded pickle files replaces `scripts/command_prep_data.sh` for preparing data. I mean can I visualize the training data right away after downloading the files?

**Comment by zemahran** [comment]
I mean can I visualize the training data right away after downloading the files?

**Comment by charlesq34** [comment]
Yes, you can!
It is equivalent to running the prep_data command
