### ISSUE TITLE
Some data_path should be fixed?

### ISSUE THREAD

**Issue by ysfalo** [charlesq34/frustum-pointnets#2]
Thanks for your excellent work! Just found some small mistakes about data_path, seems you directly use ''/home/rqi/Data/KITTI/object'' in some files, like: 
https://github.com/charlesq34/frustum-pointnets/blob/4b3a073f2377babef51c1fd661f44a9bcfbcf6e8/kitti/prepare_data.py#L338
and `rgb_detection_train/val.txt` in `kitti/rgb_detections/` folder

**Comment by charlesq34** [comment]
Hi @ysfalo thank you for pointing out that!
I had pushed a fix.
