### ISSUE TITLE
training with RGB detections?

### ISSUE THREAD

**Issue by LoFaiTh** [charlesq34/frustum-pointnets#22]
Hi, I looked up your code and I notice that you only use RGB detection result for validation. But there is a 'rgb_detection_train.txt' file, which is clearly for training. So could you release the code of generating that file or you do already have released only I did't find it?

**Comment by charlesq34** [comment]
Hi @LoFaiTh 

That file includes detection results on the training set (yes, we finetuned our 2D detector on the train set). it's not currently used for frustum pointnets training, but could be useful for 3D evaluation on the train set, or other (future) uses to tune the frustum pointnets.

unfortunately we cannot publish the 2D detector part, you can refer to the paper supplementary (https://arxiv.org/abs/1711.08488) for architecture details.
