### ISSUE TITLE
Error during Evaluation 

### ISSUE THREAD

**Issue by Sohom1997** [charlesq34/frustum-pointnets#25]
Hello @charlesq34 

Thanks for sharing your code. 

I am getting the following error during evaluation:

```
batch idx: 791
batch idx: 792
batch idx: 793
Number of point clouds: 25392
Thank you for participating in our evaluation!
Loading detections...
number of files for evaluation: 3769
ERROR: Couldn't read: 000812.txt of ground truth. Please write me an email!
An error occured while processing your results.
```

A screenshot for the same is attached as well.

Can you please help me solve the issue?

![error](https://user-images.githubusercontent.com/26880650/40846308-7ea6b210-65b9-11e8-9d72-5282369bd7b9.png)

**Comment by charlesq34** [comment]
Could you check what happens for the 000812.txt?

**Comment by Sohom1997** [comment]
Okay, it was a mistake on my part and I have resolved the issue.

The problem was that I was using the the data provided in the repository directly without copying the original KITTI data under the required directory. So the `000812.txt `(label file) was missing previously. 

Thanks for the help.

**Comment by Elena-ssq** [comment]
Hi, I've encountered the same problem here:

./evaluate_object_3d_offline groundtruth_dir /path/to/frustum-pointnets-master/train/detection_results_v1
Thank you for participating in our evaluation!
Loading detections...
number of files for evaluation: 3769
ERROR: Couldn't read: 000536.txt of ground truth. Please write me an email!
An error occured while processing your results.

The same problem arrives with 000536 during evaluation
However, the KITTI data are placed as required. Any clue why this happens?

Thanks for your help.

**Comment by yun9993** [comment]
Hello!I met the same mistake, but I don't know how to solve it.
