### ISSUE TITLE
Visualization by running kitti_object.py

### ISSUE THREAD

**Issue by HobbitLong** [charlesq34/frustum-pointnets#37]
Thanks for sharing the code of this nice work. 

It seems that the visualization code (running "python kitti/kitti_object.py") gets stuck in lin 218 on my desktop. The pedestrian in the image is visualized and then it suspends (I have waited for more than 5 minutes). I am sure my data is organized as suggested by the README file under dataset folder.

Is there any hint about such suspension? (I have tested both python2 and python3, the same) Thanks.

**Comment by Super-Tree** [comment]
Maybe you can directly comment out the code like this:
` # raw_input()`
` # Show all LiDAR points. Draw 3d box in LiDAR point cloud`
` show_lidar_with_boxes(pc_velo, objects, calib, True, img_width, img_height)`
`# raw_input()`
It works fine for me

**Comment by maxjaritz** [comment]
You have to press enter in the terminal to see the point cloud visualization.

**Comment by HobbitLong** [comment]
> You have to press enter in the terminal to see the point cloud visualization.

Oh, ya, I figured it out. Thanks, though.

**Comment by hadarsh7798** [comment]
@HobbitLong I am not able to visualize the image can you tell me what may be the problem?
