### ISSUE TITLE
How can I inference test data?

### ISSUE THREAD

**Issue by AramSo** [charlesq34/frustum-pointnets#38]
In the code,  extracted using the label already known in prepare_data. And it seems to be inference using it. How can I inference test data without labels?

**Comment by kkyan1995** [comment]
@AramSo I am also facing this problem , have you solved it ? hope you can give me a help.

**Comment by lhyfst** [comment]
It seems like the code only uses the label to get 2d proposal in training set. However, in test mode, the code uses the result of a 2d detection network to get the 2d proposal.
