### ISSUE TITLE
3D bounding box

### ISSUE THREAD

**Issue by PranjaLBiswas27** [charlesq34/frustum-pointnets#45]
Is there a tool to create 3D bounding boxes for custom dataset?

**Comment by CrazySnailer** [comment]
Maybe it's a hard problem

**Comment by PranjaLBiswas27** [comment]
But how the dataset for SUNRGBD and KITTI have been annotated, they might have used some tool I suppose?

**Comment by CrazySnailer** [comment]
yes, these annotation tool are not open source , we can use the cloudcompare to annota our data

**Comment by CrazySnailer** [comment]
@PranjaLBiswas27 but you can use https://github.com/RMonica/rviz_cloud_annotation or https://github.com/RobotLocomotion/LabelFusion to label your data.

**Comment by PranjaLBiswas27** [comment]
@CrazySnailer Thanks a lot for the info, I will try them out and hopefully they will work.

**Comment by PranjaLBiswas27** [comment]
Just to close this thread, I ended up using CloudCompare for annotating 3D ground truth bounding boxes. Although its not very convenient, but that's what I decided to work with, as I had issues getting LabelFusion to work, and rviz does not seem to help with the issue according to its developer.

**Comment by yikakabu** [comment]
@PranjaLBiswas27 Hi. Could you tell me how to use CloudCompare to annota? Did you use the 'crop' to annota the cloud by assign paraments in CloudCompare? Thanks a lot.
