### ISSUE TITLE
SUNRGBD train and val list

### ISSUE THREAD

**Issue by PranjaLBiswas27** [charlesq34/frustum-pointnets#51]
Hi,

I wanted to know where can I find the train and val text files to generate pickle files for training on SUNRGBD data. Thanks a lot in advance.

Kind Regards
Pranjal Biswas

**Comment by PranjalBiswas** [comment]
The file(allsplit.mat) can be found in the SUNRGD database which can be downloaded from there site.

**Comment by linluck1027** [comment]
Hi PranjaLBiswas27,
I have the same problem, so I should the file(allspilt.mat) and get the train and val idx and get the pickle files?
I will truely appreciate if you can share the train and val text files.

**Comment by PranjalBiswas** [comment]
@linluck1027 

I am sorry for the delayed response, but yes u need to use allsplit.mat to get the train and val splits. Since I did not work on SUNRGNBD dataset I dont have the files you require. I made my  own train and val split for my project. Hope it helps.

**Comment by shengrongjin** [comment]
Thank you for your answer . However , I also don't understand how to get the train and val splits by allsplit.mat. What should be done specifically?

**Comment by PranjalBiswas** [comment]
If you open allsplit.mat file in MATLAB, it will show you the train and val splits in the workspace.

**Comment by shengrongjin** [comment]
@PranjaLBiswas27 Firstly,thank you for your work and help! Now I have get train_data_idx.txt and val_data_idx.txt by switch allaplit.mat data. However when I execute sunrgbd_data.py, it report error Traceback (most recent call last):
  File "/home/sheng/PycharmProjects/frustum-pointnets-master/sunrgbd/sunrgbd_data/sunrgbd_data.py", line 411, in <module>
    extract_roi_seg('/data/shengData/mysunrgbd/training/val_data_idx.txt', 'training', output_filename='val_1002.zip.pickle', viz=False, augmentX=1)
  File "/home/sheng/PycharmProjects/frustum-pointnets-master/sunrgbd/sunrgbd_data/sunrgbd_data.py", line 156, in extract_roi_seg
    data_idx_list = [int(line.rstrip()) for line in open(idx_filename)]
ValueError: invalid literal for int() with base 10: '/data/shengData/mysunrgbd/SUNRGBD/kv2/kinect2data/002132_2014-06-25_21-12-39_260595134347_rgbf000085-resize'
I checking the error location ,the code are "data_idx_list = [int(line.rstrip()) for line in open(idx_filename)]"
and my train_data_idx.txt's content are string type as allsplit.mat like /data/shengData/mysunrgbd/SUNRGBD/realsense/shr/2014_12_18-16_23_17-1311000073/

Have you ever made a similar mistake? How to solve it ?

Thank you !

**Comment by debuleilei** [comment]
@shengrongjin can you tell me where you get the allsplit.mat file ? I search the SUNRGBD website with failure……

**Comment by Wujielong** [comment]
> @shengrongjin can you tell me where you get the allsplit.mat file ? I search the SUNRGBD website with failure……
SUNRGBDtoolbox\traintestSUNRGBD\allsplit.mat file

**Comment by Wujielong** [comment]
> @PranjaLBiswas27 Firstly,thank you for your work and help! Now I have get train_data_idx.txt and val_data_idx.txt by switch allaplit.mat data. However when I execute sunrgbd_data.py, it report error Traceback (most recent call last):
> File "/home/sheng/PycharmProjects/frustum-pointnets-master/sunrgbd/sunrgbd_data/sunrgbd_data.py", line 411, in
> extract_roi_seg('/data/shengData/mysunrgbd/training/val_data_idx.txt', 'training', output_filename='val_1002.zip.pickle', viz=False, augmentX=1)
> File "/home/sheng/PycharmProjects/frustum-pointnets-master/sunrgbd/sunrgbd_data/sunrgbd_data.py", line 156, in extract_roi_seg
> data_idx_list = [int(line.rstrip()) for line in open(idx_filename)]
> ValueError: invalid literal for int() with base 10: '/data/shengData/mysunrgbd/SUNRGBD/kv2/kinect2data/002132_2014-06-25_21-12-39_260595134347_rgbf000085-resize'
> I checking the error location ,the code are "data_idx_list = [int(line.rstrip()) for line in open(idx_filename)]"
> and my train_data_idx.txt's content are string type as allsplit.mat like /data/shengData/mysunrgbd/SUNRGBD/realsense/shr/2014_12_18-16_23_17-1311000073/
> 
> Have you ever made a similar mistake? How to solve it ?
> 
> Thank you !

我觉得你的 train_data_idx.txt的内容错了，应该是类似002132这种的
