### ISSUE TITLE
python/test.py code : UnicodeDecodeError: 'ascii' codec can't decode byte 0x85 in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by chowkamlee81** [charlesq34/frustum-pointnets#55]
While doing inference on the pretrained model, got an error below: **Kindly help**
Traceback (most recent call last):
  File "/home/administrator/Documents.orig/FileSystem/3D_Object_Detection/FrustrumNet/frustum-pointnets-master/train/test.py", line 50, in <module>
    from_rgb_detection=FLAGS.from_rgb_detection, one_hot=True)
  File "/home/administrator/Documents.orig/FileSystem/3D_Object_Detection/FrustrumNet/frustum-pointnets-master/train/provider.py", line 132, in __init__
    self.box2d_list = pickle.load(fp)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x85 in position 6: ordinal not in range(128)

Process finished with exit code 1

**Comment by chowkamlee81** [comment]
rename self.box2d_list = pickle.load(fp) as self.box2d_list = pickle.load(fp, encoding='latin1'). problem solved to some extent

**Comment by linhaojia13** [comment]
Hi, I meet a similar problem：
Traceback (most recent call last):
  File "provider.py", line 362, in <module>
    rotate_to_center=True, random_flip=True, random_shift=True)
  File "provider.py", line 141, in __init__
    self.box2d_list = pickle.load(fp)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 0: ordinal not in range(128)


After I did the modification as you suggested in line 141, it report another similar error:
Traceback (most recent call last):
  File "provider.py", line 362, in <module>
    rotate_to_center=True, random_flip=True, random_shift=True)
  File "provider.py", line 142, in __init__
    self.box3d_list = pickle.load(fp)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 1: ordinal not in range(128)


It seems that it doesn't work. Do you have any idea about this problem?

**Comment by linhaojia13** [comment]
I solved the problem after I make the modification as below:
                self.box2d_list = pickle.load(fp, encoding='latin1')
                self.box3d_list = pickle.load(fp, encoding='latin1')
                self.input_list = pickle.load(fp, encoding='latin1')
                self.label_list = pickle.load(fp, encoding='latin1')
                self.type_list = pickle.load(fp, encoding='latin1')
                self.heading_list = pickle.load(fp, encoding='latin1')
                self.size_list = pickle.load(fp, encoding='latin1')
and add the code in the begining of the provide.py file:

from importlib import reload
import sys
reload(sys)
