### ISSUE TITLE
Input of F-PointNet (SUNRGBD)

### ISSUE THREAD

**Issue by PranjaLBiswas27** [charlesq34/frustum-pointnets#56]
Hi,

I was going through the code as in the file 'frustum_pointnets_v1_sunrgbd.py'. In line 38 it says the input has dimensions of B * N *  4. What is B and N exactly?  And what does that input size convey exactly? Help will be really appreciated. Thanks a lot in advance.

Kind Regards
Pranjal Biswas

**Comment by wdtht** [comment]
Do you know why the dimension is  4 now? I need your help. @PranjaLBiswas27

**Comment by wdtht** [comment]
Thank you,and I found [answer](https://github.com/charlesq34/frustum-pointnets/issues/73#issue-406054400) here
