### ISSUE TITLE
Resolution of RGB and Depth Images (SUNRGBD)

### ISSUE THREAD

**Issue by PranjaLBiswas27** [charlesq34/frustum-pointnets#57]
Hi,

If I understand the code properly, is it that resolution of individual RGB and Depth images and thus the point cloud does not affect the training of F-PointNet? As the input to the network seems to be the point cloud in the field of view of the 2D box which can vary for different images and classes. And then all the data in that point cloud is re-sampled to have some constant dimensions in order to train the network. Am I correct in understanding the implementation of the network here? Please let me know. Thanks a lot in advance.

Kind Regards
Pranjal Biswas

**Comment by PranjalBiswas** [comment]
Just to close this thread, resolution of RGB and Depth images don't exactly affect much cause the input of FPN is the frustum.
