### ISSUE TITLE
Mean Sizes

### ISSUE THREAD

**Issue by PranjaLBiswas27** [charlesq34/frustum-pointnets#58]
https://github.com/charlesq34/frustum-pointnets/blob/a40690f95a9438a01d781acd5e98324cbe3e3cec/sunrgbd/sunrgbd_detection/roi_seg_box3d_dataset.py#L15

How are the mean sizes of classes defined? How can I calculate it for my custom dataset?
Please let me know. Thanks a lot in advance.

Kind Regards
Pranjal Biswas

**Comment by PranjalBiswas** [comment]
In order to close this thread, we can calculate the mean sizes using this file:

>  frustum-pointnets/sunrgbd/sunrgbd_data/cluster_box3d.py
