### ISSUE TITLE
Sth error on Evaluation

### ISSUE THREAD

**Issue by zuomaidi52** [charlesq34/frustum-pointnets#59]
Hi，thanks for your job！
when I run `CUDA_VISIBLE_DEVICES=0 sh scripts/command_test_v1.sh`, I got some files in `detection_results_v1`, but the `*.txt` file in `detection_results_v1/data` are empty, could anyone give me some questions?
ps: my `*.pickle` file and dataset are downloaded by the README.

**Comment by kwea123** [comment]
Can you paste the error message?
Also, did you download the KITTI dataset and put in the correct folder as suggested [here](https://github.com/charlesq34/frustum-pointnets/tree/master/dataset)?

**Comment by zuomaidi52** [comment]
when I run `CUDA_VISIBLE_DEVICES=0 sh scripts/command_test_v1.sh`, I got this msg:
![2018-10-11 13-59-40](https://user-images.githubusercontent.com/12689568/46783939-c3c6b680-cd5e-11e8-82de-f48da977e30e.png)
My dataset is download from the KITTI object page and put it in folder what the `dataset/README.md` said.
@kwea123

**Comment by kwea123** [comment]
The `Number of point clouds` should be something around 25000, but you only have 16. It seems that the .pickle files are corrupted or not complete? Can you check the size of the .pickle files (in particular the rgb_detection) ? And also try to create it on your own (by running `sh scripts/command_prep_data.sh`) and try to evaluate it again.

**Comment by zuomaidi52** [comment]
sizeof(frustum_carpedcyc_train.pickle) = 3.4GB;
sizeof(frustum_carpedcyc_val.pickle) = 859.9MB;
sizeof(frustum_carpedcyc_val_rgb_detection.pickle) = 659.4MB;
And I download the `*.pickle` again, then run the `CUDA_VISIBLE_DEVICES=0 sh scripts/command_test_v1.sh`, the result is unchanged. 

ps: the download link in README.md:

![default](https://user-images.githubusercontent.com/12689568/46789468-14dea680-cd6f-11e8-9ccf-6b58a70a73bb.png)

------
By running `sh scripts/command_prep_data.sh` create `*.pickle` files.
sizeof(frustum_carpedcyc_train.pickle) = 1.1GB;
sizeof(frustum_carpedcyc_val.pickle) = 283.5MB;
sizeof(frustum_carpedcyc_val_rgb_detection.pickle) = 247.7MB;

I running the `CUDA_VISIBLE_DEVICES=0 sh scripts/command_test_v1.sh` use the `*.pickle` that created by `sh scripts/command_prep_data.sh`,the result seems unchanged.

**Comment by zuomaidi52** [comment]
@kwea123 I have solved this question.Because I have modified some code in `test.py`. Thank you for your reply.

**Comment by QZ1219** [comment]
> @kwea123 I have solved this question.Because I have modified some code in `test.py`. Thank you for your reply.
@zuomaidi52  Do you know why command_prep_data.sh produce sizeof(frustum_carpedcyc_train.pickle) = 1.1GB;sizeof(frustum_carpedcyc_val.pickle) = 283.5MB;sizeof(frustum_carpedcyc_val_rgb_detection.pickle) = 247.7MB;

but  the download link in README.md sizeof(frustum_carpedcyc_train.pickle) = 3.4GB;sizeof(frustum_carpedcyc_val.pickle) = 859.9MB;sizeof(frustum_carpedcyc_val_rgb_detection.pickle) = 659.4MB;

Do you know why ?Waiting for your reply!

**Comment by kwea123** [comment]
Those are the correct sizes. What error do you encounter?

Did you change any code?

**Comment by QZ1219** [comment]
> Those are the correct sizes. What error do you encounter?
> 
> Did you change any code?

 download the *.pickle ,the files size have about 4.5G , but when I running the prep_data command to produce it. it only about 1.54G.

**Comment by kwea123** [comment]
The downloaded files are correct.
I don't know why you both can't get the same thing by running prep_data; personally I get the same thing..

Have you downloaded the whole dataset and put in the right directory?
Or probably it's the Python version which is not good. Are you using Python 2.7?

**Comment by QZ1219** [comment]
> The downloaded files are correct.
> I don't know why you both can't get the same thing by running prep_data; personally I get the same thing..
> 
> Have you downloaded the whole dataset and put in the right directory?
> Or probably it's the Python version which is not good. Are you using Python 2.7?

using python 3.6.  I will check my dataset and how to produce the *.pickle

**Comment by kwea123** [comment]
The author is using 2.7, so I think you need to try 2.7

**Comment by WangGangUCAS** [comment]
> > The downloaded files are correct.
> > I don't know why you both can't get the same thing by running prep_data; personally I get the same thing..
> > Have you downloaded the whole dataset and put in the right directory?
> > Or probably it's the Python version which is not good. Are you using Python 2.7?
> 
> using python 3.6. I will check my dataset and how to produce the *.pickle

How do you solve this problem?
