### ISSUE TITLE
size of  file        *.pickle  

### ISSUE THREAD

**Issue by QZ1219** [charlesq34/frustum-pointnets#62]
Hello charlesq,Thank you for great work.
I have a discredit.   download the *.pickle  ,it have about 4.5G  , but when I running the prep_data command to produce it.  it only about 1.54G.
Do you know why ?
Waiting for your reply!

**Comment by jl626** [comment]
It is because they used different encodings to dump data. I guess you are using python 3. No worries, it still contains the same data.

**Comment by QZ1219** [comment]
> It is because they used different encodings to dump data. I guess you are using python 3. No worries, it still contains the same data.

thank you !
