### ISSUE TITLE
"global name 'in_hull' is not defined" in utils.py: error while sunrgb setup

### ISSUE THREAD

**Issue by nguptaHQ** [charlesq34/frustum-pointnets#70]
While running sunrgbd_data.py
Getting below error:
"global name 'in_hull' is not defined" in utils.py

Please help

**Comment by linluck1027** [comment]
The same problem @charlesq34  
Please help

**Comment by PranjalBiswas** [comment]
Hi,

I am not @charlesq34 , but you can use the same function defined for Kitti here:

https://github.com/charlesq34/frustum-pointnets/blob/889c277144a33818ddf73c4665753975f9397fc4/kitti/prepare_data.py#L23

**Comment by linluck1027** [comment]
Thank a lot @PranjaLBiswas27

**Comment by nguptaHQ** [comment]
Thanks a lot @PranjaLBiswas27.

**Comment by nguptaHQ** [comment]
#69 
@PranjaLBiswas27
Could you provide pre-trained weights for SUNRGBD dataset if you have?

**Comment by PranjalBiswas** [comment]
@gangooteli , I did not train FPN on SUNRGBD dataset so I don't have the weights that you need.

Update: FPN - Frustum Pointnet (in this case) not Feature Pyramid Networks.

**Comment by nguptaHQ** [comment]
@PranjaLBiswas27 For training and validation, I don't think we need FPN, since it is taking xmin,ymin,xmax,ymax from labels itself while we create pickle file for training and testing in sunrgb_data.py

See below lines of code:
[https://github.com/charlesq34/frustum-pointnets/blob/2ffdd345e1fce4775ecb508d207e0ad465bcca80/sunrgbd/sunrgbd_data/sunrgbd_data.py#L191](url)
 [https://github.com/charlesq34/frustum-pointnets/blob/2ffdd345e1fce4775ecb508d207e0ad465bcca80/sunrgbd/sunrgbd_data/utils.py#L19](url)

Only for testing, we need to get detections.

**Comment by PranjalBiswas** [comment]
Yes FPN needs 2D bounding boxes for proposing frustums. What weights are you asking for in that case?

**Comment by nguptaHQ** [comment]
@PranjaLBiswas27 I am asking for the final trained weights for predicting 3d bounding boxes using frustum pointnet while training on SUNRGBD dataset.
If you have, please provide?
For 2d detector, I can use some other pre-trained weigths

**Comment by PranjalBiswas** [comment]
@gangooteli , Yes that is what I mentioned, I did not train FPN (predicts 3D bounding boxes) on SUNRGBD dataset. FPN network is required for training and validation as well and not just for training contrary to what you have mentioned. Check,
1. sunrgbd_detection/train_one_hot.py: Calls fpnv1 for training.
2. sunrgbd_detection/test_one_hot.py: Calls fpnv1 for testing.

**Comment by nguptaHQ** [comment]
@PranjaLBiswas27 Thanks got what you are saying.
Confused as FPN(Feature Pyramid Network) is 2d detector if you will read Frustum research paper. 

FPN(predicts 3d bounding box) which you are taking is basically frustum point network.
