### ISSUE TITLE
Can I download pickle files directly?

### ISSUE THREAD

**Issue by Rocalman** [charlesq34/frustum-pointnets#9]
Hi! @charlesq34 
Can I download pickle files directly?Kitti dataset is too big and there is not enough disk space. Can I ignore this step of data conversion? Thanks.

**Comment by charlesq34** [comment]
@Rocalman 

Here you go!

https://1drv.ms/u/s!ApbTjxa06z9CgReyql8fsNz6SnXa

You need to download, unzip and move the pickle files to `kitti` folder.
